version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"          
    volumes:
    ### Set the working directory to the app and copy files there
      - .:/app
    depends_on:
      - db
    ### This is needed to insure that the web can restart and connect to the DN      
    restart: always         
    # This will
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
 
  db:
    image: postgres
    ports:
      - "5432:5432"   
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dogserverdb
    volumes:
    # This is apparently just the standard so that it will persist the data.
      - db-data:/var/lib/postgresql/data
 
volumes:
  db-data:    
     

        

      
