version: '3.8'

services:
  web:
    build: .
    image: dogserver    
    ports:
      - "8080:8080"          
    volumes:
      - .:/code
    depends_on:
      - db                 
    networks:
      - app-network         

  db:
    image: postgres
    ports:
      - "5432:5432"   
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dogserver
    volumes:
      - db-data:/data  
    networks:
      - app-network       
volumes:
  db-data:                

networks:
  app-network:          

# Command  not needed?